/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import view.interfaces.ViewInterface;
import view.interfaces.BalanceObserver;

/**
 *
 * @author gustavoavelar
 */
public class HomeView extends javax.swing.JFrame implements ViewInterface{
    /**
     * Creates new form TelaInicio
     */
    public HomeView() {
        initComponents();
        this.setTitle("LGC Finance");
    }
    
    @Override
    public void addBtnAction(JButton btn, ActionListener action) {
        btn.addActionListener(action);
    }
    
    public JButton getBtnIncome() {
        return this.btnAddIncome;
    }
    
    public JButton getBtnExpenditure() {
        return this.btnAddExpenditure;
    }
    
    public JButton getBtnHistory() {
        return this.btnHistory;
    }
    
    @Override
    public void showView() {
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddExpenditure = new javax.swing.JButton();
        btnAddIncome = new javax.swing.JButton();
        lbBalance = new javax.swing.JLabel();
        lbCurrentBalance = new javax.swing.JLabel();
        btnHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddExpenditure.setText("Adicionar Despesa");

        btnAddIncome.setText("Adicionar Ganho");

        lbBalance.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbBalance.setText("Saldo:");

        lbCurrentBalance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCurrentBalance.setText("R$1900");

        btnHistory.setText("Histórico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCurrentBalance))
                    .addComponent(btnAddIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddExpenditure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBalance)
                    .addComponent(lbCurrentBalance))
                .addGap(44, 44, 44)
                .addComponent(btnAddExpenditure)
                .addGap(18, 18, 18)
                .addComponent(btnAddIncome)
                .addGap(18, 18, 18)
                .addComponent(btnHistory)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpenditure;
    private javax.swing.JButton btnAddIncome;
    private javax.swing.JButton btnHistory;
    private javax.swing.JLabel lbBalance;
    private javax.swing.JLabel lbCurrentBalance;
    // End of variables declaration//GEN-END:variables

    public void updateBalance(Double amount) {
        this.lbBalance.setText(amount.toString());
    }
}
